name: The Grid Really Sucks
favicon: null
layout_spectrum: 0.07067537773400545
typography_spectrum: 0.2536366635467857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6297802506014705
  lightness: 0.9675778253003955
  saturation: 0.6749091306701303
  rhythmicContrast: 0.6487740238662809
purpose: []
